object Versions {
    const val androidXAppcompat = "1.3.1"
    const val androidXCoreKtx = "1.5.0-beta02"
    const val androidXConstraintLayout = "2.0.4"
    const val androidXLegacyV4 = "1.0.0"
    const val androidXFragmentKtx = "1.4.1"
    const val androidXActivityKtx = "1.4.0"
    const val androidXLifecycleExt = "2.2.0"
    const val androidXLifecycleScope = "2.5.1"
    const val androidXLivedata = "2.3.1"
    const val androidXCardView = "1.0.0"
    const val androidXRecyclerView = "1.2.1"
    const val androidXWorkManager = "2.7.1"
    const val androidXSwipeRefreshLayout = "1.1.0"
    const val androidXTestCore = "1.2.0"
    const val androidXTestRules = "1.2.0"
    const val androidXTestJUnit = "1.1.1"
    const val androidXTestEspresso = "3.3.0-alpha04"
    const val androidXTestRunner = "1.3.0-alpha04"
    const val androidXTestTruth = "1.4.0"
    const val androidXCoreTesting = "2.1.0"
    const val mockito = "3.3.0"
    const val mockitoKotlin = "2.2.0"
    const val json = "20190722"
    const val powerMockito = "2.0.5"
    const val jUnit = "4.13"
    const val googleMaterial = "1.6.1"
    const val coroutines = "1.6.2"
    const val coroutinesTest = "1.3.3"
    const val kotlinJdk = "1.5.31"
    const val daggerHilt = "2.44"
    const val retrofit2 = "2.8.1"
    const val okhttp3 = "4.5.0"
    const val gson = "2.8.7"
}

//third party libraries
object ThirdPartyLibVersions {
    const val glide = "4.11.0"
    const val testThreetenabp = "1.6.3"
    const val regularThreetenabp = "1.4.0"
    const val timber = "4.7.1"
    const val chucker = "3.5.2"
    const val leakCanary = "2.8.1"
    const val turbine = "0.8.0"
}
